name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: barichello/godot-ci:4.6
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import project resources
        run: godot --path . --headless --import

      - name: Export game to Web
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html

      - name: Upload web build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  deploy-pages:
    name: Deploy to GitHub Pages
    needs: export-web
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
